# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 15:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderQuizScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easiness_factor', models.FloatField(help_text='From 1.3 (hard) to 2.5 (easy)')),
                ('consecutive_correct', models.IntegerField(help_text='Zero or greater')),
                ('interval', models.IntegerField(help_text='One or greater')),
                ('review_date', models.DateTimeField(auto_now=True)),
                ('quality_0', models.IntegerField(default=0)),
                ('quality_1', models.IntegerField(default=0)),
                ('quality_2', models.IntegerField(default=0)),
                ('quality_3', models.IntegerField(default=0)),
                ('quality_4', models.IntegerField(default=0)),
                ('quality_5', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Gender Quiz Scores',
            },
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, help_text='Enter popularity rank (1=most popular)', null=True)),
                ('noun', models.CharField(help_text='Enter noun', max_length=64, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Masculine'), ('N', 'Neuter'), ('F', 'Feminine')], max_length=1)),
                ('genitive', models.CharField(blank=True, help_text='Enter genitive form', max_length=64)),
                ('plural', models.CharField(blank=True, help_text='Enter plural form', max_length=64)),
                ('english', models.TextField(blank=True, help_text='Enter English translation(s)')),
            ],
            options={
                'ordering': ['noun'],
            },
        ),
        migrations.AddField(
            model_name='genderquizscore',
            name='noun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deklination.Noun'),
        ),
        migrations.AddField(
            model_name='genderquizscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
